{% set version = "0.5.1" %}

package:
  name: s3fs
  version: {{ version }}

source:
  fn: s3fs-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/s3fs/s3fs-{{ version }}.tar.gz
  sha256: 7396943cbc1cf92eb6f7aa93be5f64a3bfa59d76908262e89bae06e3c87fa59d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  build:
    - python >=3.6
    - setuptools
    - pip

  run:
    - python >=3.6
    - aiobotocore
    - botocore
    - fsspec >=0.8.0


test:
  imports:
    - s3fs

about:
  home: http://s3fs.readthedocs.io/en/latest/
  license: BSD 3-Clause
  summary: Convenient Filesystem interface over S3
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - martindurant
    - mrocklin
    - koverholt
    - tomaugspurger
