{% set version = "0.5.2" %}

package:
  name: s3fs
  version: {{ version }}

source:
  fn: s3fs-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/s3fs/s3fs-{{ version }}.tar.gz
  sha256: 87e5210415db17b9de18c77bcfc4a301570cc9030ee112b77dc47ab82426bae1

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip

  run:
    - python >=3.6
    - aiobotocore
    - botocore
    - fsspec >=0.8.0


test:
  imports:
    - s3fs

about:
  home: http://s3fs.readthedocs.io/en/latest/
  license: BSD 3-Clause
  summary: Convenient Filesystem interface over S3
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - martindurant
    - mrocklin
    - koverholt
    - tomaugspurger
