{% set version = "0.3.0" %}
 
package:
  name: s3fs
  version: "{{ version }}"

source:
  fn: s3fs-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/s3fs/s3fs-{{ version }}.tar.gz
  sha256: 6c87cadd0eca4ffff5a251b0df55a08bc33bf4af0bf5bd567b39d842d024a9f5

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python

requirements:
  build:
    - python
    - setuptools
    - boto3
    - pip

  run:
    - python
    - boto3


test:
  imports:
    - s3fs

about:
  home: http://s3fs.readthedocs.io/en/latest/
  license: BSD 3-Clause
  summary: 'Convenient Filesystem interface over S3'

extra:
  recipe-maintainers:
    - martindurant
    - mrocklin
    - koverholt
