{% set version = "2021.9.0" %}

package:
  name: s3fs
  version: {{ version }}

source:
  fn: s3fs-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/s3fs/s3fs-{{ version }}.tar.gz
  sha256: 9f80fccea6870d4ff65dae77bad01a818320cbcc3d8c2b4b0695341e1343c92e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip

  run:
    - python >=3.6
    - aiobotocore ==1.4.0
    - botocore
    - fsspec ==2021.8.1


test:
  requires:
    - pip
  imports:
    - s3fs
  commands:
    - pip check

about:
  home: http://s3fs.readthedocs.io/en/latest/
  license: BSD-3-Clause
  summary: Convenient Filesystem interface over S3
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - martindurant
    - mrocklin
    - koverholt
    - tomaugspurger
