{% set name = "s3fs" %}
{% set version = "2023.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/s3fs-{{ version }}.tar.gz
  sha256: 35057d4d59722cab9fe91c9a30147e3e5bddfc55ec14fde8776c512179c823dd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - aiobotocore >=2.5.0,<2.5.1
    - aiohttp
    - fsspec =={{ version }}
    - python >=3.8

test:
  imports:
    - s3fs
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://s3fs.readthedocs.io/en/latest/
  summary: Convenient Filesystem interface over S3
  license: BSD-3-Clause
  license_file: LICENSE.txt
  dev_url: https://github.com/dask/s3fs
  doc_url: https://s3fs.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - martindurant
    - mrocklin
    - tomaugspurger
