{% set name = "s3fs" %}
{% set version = "2026.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/s3fs-{{ version }}.tar.gz
  sha256: 91cb2a9f76e35643b76eeac3f47a6165172bb3def671f76b9111c8dd5779a2ac

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - aiobotocore >=2.19.0,<4.0.0
    - aiohttp
    - fsspec =={{ version }}
    - python >={{ python_min }}

test:
  imports:
    - s3fs
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://s3fs.readthedocs.io/en/latest/
  summary: Convenient Filesystem interface over S3
  license: BSD-3-Clause
  license_file: LICENSE.txt
  dev_url: https://github.com/dask/s3fs
  doc_url: https://s3fs.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - martindurant
    - mrocklin
    - tomaugspurger
