{% set name = "s3fs" %}
{% set version = "2025.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/s3fs-{{ version }}.tar.gz
  sha256: 8ddbdc83c98ed55c7397a295596a7106de6f7a126c45798a95ad4d280edb3611

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - aiobotocore >=2.5.4,<3.0.0
    - aiohttp
    - fsspec =={{ version }}
    - python >={{ python_min }}

test:
  imports:
    - s3fs
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://s3fs.readthedocs.io/en/latest/
  summary: Convenient Filesystem interface over S3
  license: BSD-3-Clause
  license_file: LICENSE.txt
  dev_url: https://github.com/dask/s3fs
  doc_url: https://s3fs.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - martindurant
    - mrocklin
    - tomaugspurger
