{% set name = "s3fs" %}
{% set version = "2023.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/s3fs-{{ version }}.tar.gz
  sha256: c40f238ccc9fefff3f6d09d4b5762abd6c913ba42e1a328976b54d038901b835

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - aiobotocore >=2.7.0,<2.7.1
    - aiohttp
    - fsspec =={{ version }}
    - python >=3.8

test:
  imports:
    - s3fs
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://s3fs.readthedocs.io/en/latest/
  summary: Convenient Filesystem interface over S3
  license: BSD-3-Clause
  license_file: LICENSE.txt
  dev_url: https://github.com/dask/s3fs
  doc_url: https://s3fs.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - martindurant
    - mrocklin
    - tomaugspurger
