{% set version = "0.3.4" %}
 
package:
  name: s3fs
  version: "{{ version }}"

source:
  fn: s3fs-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/s3fs/s3fs-{{ version }}.tar.gz
  sha256: 81e92de5448a40dd2fcc26ef86c314bb368bed9dd84a48f448d2d6406d9c0d84

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python

requirements:
  build:
    - python >=3.5
    - setuptools
    - boto3
    - pip

  run:
    - python >=3.5
    - boto3
    - fsspec


test:
  imports:
    - s3fs

about:
  home: http://s3fs.readthedocs.io/en/latest/
  license: BSD 3-Clause
  summary: 'Convenient Filesystem interface over S3'
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - martindurant
    - mrocklin
    - koverholt
